### ISSUE TITLE
Install link is broken

### ISSUE THREAD

**Issue by raphamorim** [dracula/rio-terminal#2]
Hey there @luxonauta , can you guide me how fix it for the website. Since https://draculatheme.com/rio is not available.

**Comment by luxonauta** [comment]
Thanks for the report; I will fix it!

**Comment by raphamorim** [comment]
Thank you @luxonauta 🙏 🙏 🙏

**Comment by luxonauta** [comment]
🥳 Fixed: https://draculatheme.com/rio-terminal

**Comment by raphamorim** [comment]
🎖️ thank you @luxonauta !!
