### ISSUE TITLE
Path to copy Theme is wrong

### ISSUE THREAD

**Issue by danielcs88** [dracula/rio-terminal#3]
This info is wrong

<img width="731" alt="image" src="https://github.com/dracula/rio-terminal/assets/13838845/0c0721ba-70fd-4dfd-9008-292184542887">

<img width="712" alt="Screenshot 2023-11-22 at 12 06 49 PM" src="https://github.com/dracula/rio-terminal/assets/13838845/19c98251-a2b4-47a5-b541-2cac0ebb2407">

Per Rio's `config.toml` file

> ```
> # Theme
> #
> # It makes Rio look for the specified theme in the themes folder
> # (macos and linux: ~/.config/rio/themes/dracula.toml)
> # (windows: C:\Users\USER\AppData\Local\rio\themes\dracula.toml)
> ```

**Comment by YuerLee** [comment]
#4 fixed it but the [website](https://draculatheme.com/rio-terminal) still show the incorrect one.
